CREATE DATABASE employees;

CREATE TABLE employee(
    emp_id INT PRIMARY KEY,
    FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(20),
    SALARY INT,
    JOINING_DATE DATE,
    DEPARTMENT VARCHAR(20)

);